# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKsRxVlzxsUBJVrrczWZMlbiCaomcDJj
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# 1. โหลดโมเดลที่เตรียมไว้
model = joblib.load('starbucks_model.pkl')

# 2. ตั้งค่าหน้าตาแอป
st.set_page_config(page_title="Starbucks Wait Time Predictor", page_icon="☕")
st.title("☕ Starbucks Wait Time Predictor")
st.write("พยากรณ์เวลารับเครื่องดื่มด้วย Machine Learning")

# 3. ส่วนรับข้อมูลจากผู้ใช้
st.sidebar.header("Input Data")
cart_size = st.sidebar.number_input("จำนวนแก้ว (Cart Size)", min_value=1, max_value=20, value=1)
hour = st.sidebar.slider("ช่วงเวลาที่สั่ง (Hour)", 0, 23, 12)

# 4. ส่วนการพยากรณ์
if st.button("Predict Wait Time"):
    # สร้าง Input สำหรับโมเดล (ต้องเรียง Column ให้เหมือนตอนเทรน)
    input_data = pd.DataFrame([[cart_size, hour]], columns=['cart_size', 'hour'])

    # พยากรณ์ค่าพื้นฐาน (Base Prediction)
    prediction = model.predict(input_data)[0]

    # 5. ใส่ Dynamic Buffer ตาม Insight ที่เราวิเคราะห์
    # ช่วง Peak หรือ ช่วงที่ R2 ผันผวน (เช่น 23, 0, 1) เราจะเพิ่ม Buffer ให้กว้างขึ้น
    if hour in [23, 0, 1]:
        buffer_min = 0.5
        buffer_max = 3.5  # เพิ่มช่วงกว้างขึ้นเพราะ R2 ต่ำ
    elif hour in [10, 15, 16]: # ช่วง Peak
        buffer_min = 1.0
        buffer_max = 4.0
    else:
        buffer_min = 0.5
        buffer_max = 2.0

    lower_bound = max(1, prediction - buffer_min) # ไม่ให้ต่ำกว่า 1 นาที
    upper_bound = prediction + buffer_max

    # 6. แสดงผล
    st.success(f"### เวลารอโดยประมาณ: {lower_bound:.1f} - {upper_bound:.1f} นาที")

    # คำแนะนำเพิ่มเติมสำหรับผู้ใช้
    if hour in [23, 0, 1]:
        st.warning("⚠️ เป็นช่วงใกล้ปิดร้าน เวลารออาจมีความผันผวนสูงกว่าปกติ")
    st.info(f"โมเดลคำนวณจากจำนวน {cart_size} แก้ว ในช่วงเวลา {hour}:00 น.")

# ส่วนท้าย (Footer)
st.markdown("---")
st.caption("Developed for ML Deployment Project")